#!/usr/bin/perl

$shmid=shmget(20,undef,0100666);
for(;;)
{
	print 'input zip code->';
	$input=<STDIN>;
	chomp $input;
	$flag=0;
	foreach $i(0..123803)
	{
		$head=100*$i;
		shmread($shmid,$zip,$head,7);
		($input eq $zip)&&($flag=1)&&(last);
	}
	if($flag==0)
	{
		print "not found\n";
	}
	else
	{
		$head=$head+7;
		shmread($shmid,$address,$head,93);
		print "$address\n";
	}
}