#! /usr/bin/perl

#lesson6を改造
$SIG{'CLD'} = 'killzombi';
$file='/home/koara/bin/table.csv';
open(READ,"$file");
for(;;){
	print '->';
	$input=<STDIN>;
	chomp $input;
	seek(READ,0,0);
	unless(fork){
		while(<READ>){
			chomp $_;
			($input eq '') || ($_=~m/$input/)&&(print "$_\n");
		}
		exit 0;
	}
}

close(READ);

sub killzombi{
	wait;
}
